### ISSUE TITLE
Recent change in discourse-expose-emails-in plugin breaks category views

### ISSUE THREAD

**Issue by k4rtik** [mozilla/discourse#223]
Hi

I use this plugin in a self-hosted instance of Discourse, but the most recent change at https://github.com/mozilla/discourse-expose-emails-in/commit/07eb77c2b8bc2af7b493a1572ee131c4f8be8e66 has led to those category pages that have no emails in defined to not render.

This is the error I see in /logs:
## Message
```
Uncaught TypeError: Cannot read property 'split' of null
Url: https://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008f0074c14a8993aa81f29017aff8c77d204d91.js
Line: 1
Column: 3545
Window Location: https://discuss.example.com/c/site-feedback
```

## Backtrace
```
TypeError: Cannot read property 'split' of null
    at n.setupComponent (https://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008f0074c14a8993aa81f29017aff8c77d204d91.js:1:3545)
    at n.init (https://discuss.example.com/assets/application-eed5b78fdf9e42a827d8a25de7e8c97db3160df769414206bcc9a86fe7a5eedd.js:34:1589)
    at n [as init] (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:10:4406)
    at c (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:9:28943)
    at Function.e.create (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:9:30816)
    at e.n.create (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:3:31978)
    at t.o.create (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:5:17486)
    at Object.evaluate (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:14:16271)
    at e.t.evaluate (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:14:2818)
    at e.t.evaluateSyscall (https://discuss.example.com/assets/ember_jquery-d430881a3fb1403871256e5a02423c4b20a78793685e92088613ca9a701baf88.js:15:1375)
```

## Env
hostname | discuss-app
-- | --
process_id | 201
application_version | d64908ba27fb72bddab18ffba80ae2ad7b190957
HTTP_HOST | discuss.example.com
REQUEST_URI | /logs/report_js_error
REQUEST_METHOD | POST
HTTP_USER_AGENT | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
HTTP_ACCEPT | */*
HTTP_REFERER | https://discuss.example.com/c/site-feedback
HTTP_X_FORWARDED_FOR | xxx.xxx.xxx.xxx
HTTP_X_REAL_IP | xxx.xxx.xxx.xxx
  | paramsmessageUncaught TypeError: Cannot read property 'split' of nullurlhttps://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008line1column3545window_locationhttps://discuss.example.com/c/site-feedbackstacktraceTypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example.. | params | messageUncaught TypeError: Cannot read property 'split' of nullurlhttps://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008line1column3545window_locationhttps://discuss.example.com/c/site-feedbackstacktraceTypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example.. | message | Uncaught TypeError: Cannot read property 'split' of null | url | https://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008 | line | 1 | column | 3545 | window_location | https://discuss.example.com/c/site-feedback | stacktrace | TypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example..
params | messageUncaught TypeError: Cannot read property 'split' of nullurlhttps://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008line1column3545window_locationhttps://discuss.example.com/c/site-feedbackstacktraceTypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example.. | message | Uncaught TypeError: Cannot read property 'split' of null | url | https://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008 | line | 1 | column | 3545 | window_location | https://discuss.example.com/c/site-feedback | stacktrace | TypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example..
message | Uncaught TypeError: Cannot read property 'split' of null
url | https://discuss.example.com/assets/plugins/discourse-expose-emails-in-2acc91cd20bee56ed6256f39008
line | 1
column | 3545
window_location | https://discuss.example.com/c/site-feedback
stacktrace | TypeError: Cannot read property 'split' of null at n.setupComponent (https://discuss.example..

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/DISC-12)

**Comment by LeoMcA** [comment]
Thanks for reporting, this was an oversight.

Fixed with https://github.com/mozilla/discourse-expose-emails-in/commit/e4e92b02bd150c72585eba232a27aa4bf9e7f5fb
